// SPDX-License-Identifier: Apache-2.0
//
// Copyright 2026 The Bouclier Bleu Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use anyhow::Result;
use std::collections::HashMap;
use std::sync::mpsc;
use std::time::Duration;
use std::sync::Arc;
use std::any::Any;

use modules::SecurityModule;

pub mod ipc;

/*
 * The dynamic loader generated by `build.rs` is injected into an isolated 
 * module namespace. This prevents trait and import pollution inside the main
 * daemon.
 */
#[allow(clippy::all)]
pub mod bpf_loader {
    include!(concat!(env!("OUT_DIR"), "/bpf_loader.rs"));
}

fn main() -> Result<()> {
    println!("🛡️ Starting Bouclier Bleu Core Engine...");

    /*
     * REGISTRY INITIALIZATION:
     * The userland registry acts as the logical abstraction layer for defense
     * rules.
     * Wrapping these in Arc ensures safe, read-only concurrent access across
     * our asynchronous worker threads, adhering strictly to Rust's memory
     * safety guarantees.
     */
    let registry: Vec<Arc<dyn SecurityModule + Send + Sync>> = modules::build_registry();
    let shared_registry = Arc::new(registry);

    /*
     * KERNEL MEMORY LIFECYCLE:
     * We maintain active eBPF skeletons strictly in memory. Dropping these 
     * file descriptors would instruct the kernel to abruptly detach the BPF
     * hooks.
     * For real-time state manipulation (toggling on/off), we now synchronize 
     * state directly into the kernel's maps to avoid performance bottlenecks
     * and fail-open race conditions associated with rapid attach/detach
     * cycles.
     */
    let mut active_skeletons: HashMap<String, Box<dyn Any>> = HashMap::new();

    for mod_name in bpf_loader::available_modules() {
        if let Ok(skel) = bpf_loader::load_module(mod_name) {
            println!("· Loaded and Attached eBPF module: {}", mod_name);
            
            // Synchronize initial enforcement state directly into the kernel
            if let Err(e) = bpf_loader::set_module_state(&*skel, mod_name, true) {
                println!("· [Warning] Failed to initialize kernel state map for {}: {}", mod_name, e);
            }

            active_skeletons.insert(mod_name.to_string(), skel);
            
            if let Some(user_mod) = shared_registry.iter().find(|m| m.slug() == mod_name) {
                user_mod.toggle(true);
            }
        }
    }
    println!("· [Success] All defensive eBPF modules loaded and attached.");

    /*
     * IPC CONTROL PLANE:
     * Establishes a Multi-Producer, Single-Consumer (mpsc) channel following 
     * the Actor Model. The main thread retains exclusive mutation rights over 
     * kernel skeletons and BPF maps, thereby preventing data races.
     */
    let (tx, rx) = mpsc::sync_channel(128);
    ipc::start_ipc_server(tx);
    println!("· [Success] Engine is running securely.");

    println!("· Run: # cat /sys/kernel/tracing/trace_pipe in another terminal to see alerts.");
    println!("Press Ctrl+C to exit.");

    // Main Engine Event Loop
    loop {
        while let Ok(msg) = rx.try_recv() {
            let response = match msg.cmd {
                
                ipc::DaemonCmd::Status => "Bouclier Bleu EDR Status: Kernel Engine Running\n".to_string(),
                
                ipc::DaemonCmd::List => {
                    let mut out = String::from("MODULE REGISTRY:\n");
                    for module in shared_registry.iter() {
                        let state = if module.status() { "[ACTIVE]  " } else { "[INACTIVE]" };
                        out.push_str(&format!(" {} {} ({})\n", state, module.slug(), module.name()));
                    }
                    out
                }
                
                ipc::DaemonCmd::Enable(target) => {
                    if let Some(skel) = active_skeletons.get(&target) {
                        // FAST PATH
                        // Sync the `state_map` directly. No kernel
                        // reallocation needed.
                        match bpf_loader::set_module_state(&**skel, &target, true) {
                            Ok(_) => {
                                if let Some(user_mod) = shared_registry.iter().find(|m| m.slug() == target) {
                                    user_mod.toggle(true);
                                }
                                format!("SUCCESS: Defense module '{}' has been ENABLED via state_map synchronization\n", target)
                            }
                            Err(e) => format!("ERROR: Failed to update kernel state for '{}': {}\n", target, e),
                        }
                    } else {
                        // SLOW PATH
                        // Complete reload of the BPF program into the kernel
                        // if it crashed or was absent.
                        match bpf_loader::load_module(&target) {
                            Ok(skel) => {
                                if let Err(e) = bpf_loader::set_module_state(&*skel, &target, true) {
                                    // Evaluate to the error string directly without using `return`
                                    format!("ERROR: Failed to set kernel state for {}. Aborting enablement: {}\n", target, e)
                                } else {
                                    active_skeletons.insert(target.clone(), skel);
                                    if let Some(user_mod) = shared_registry.iter().find(|m| m.slug() == target) {
                                    user_mod.toggle(true);
                                    }
                                    format!("SUCCESS: Defense module '{}' has been ENABLED and ATTACHED\n", target)
                                }
                            }
                            Err(e) => format!("ERROR: Failed to load module '{}': {}\n", target, e),
                        }
                    }
                }
                
                ipc::DaemonCmd::Disable(target) => {
                    /*
                     * REAL-TIME KERNEL SYNCHRONIZATION:
                     * Instead of completely detaching the eBPF hook (which
                     * induces high latency and potential fail-open
                     * vulnerabilities), we utilize the high-speed `state_map`
                     * to toggle the enforcement logic seamlessly while
                     * maintaining our connection to the BPF telemetry stream.
                     */
                    if let Some(skel) = active_skeletons.get(&target) {
                        match bpf_loader::set_module_state(&**skel, &target, false) {
                            Ok(_) => {
                                if let Some(user_mod) = shared_registry.iter().find(|m| m.slug() == target) {
                                    user_mod.toggle(false);
                                }
                                format!("SUCCESS: Defense module '{}' has been DISABLED via state_map synchronization\n", target)
                            }
                            Err(e) => format!("ERROR: Failed to update kernel state for '{}': {}\n", target, e),
                        }
                    } else {
                        format!("ERROR: Module '{}' is not currently active\n", target)
                    }
                }
            };
            
            let _ = msg.reply.send(response);
        }

        // To be replaced by `RingBuffer::poll` for processing eBPF telemetry
        // events.
        std::thread::sleep(Duration::from_millis(50));
    }
}
