// SPDX-License-Identifier: Apache-2.0
//
// Copyright 2026 The Bouclier Bleu Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use anyhow::Result;
use std::thread;
use std::time::Duration;

use libbpf_rs::skel::{OpenSkel, Skel, SkelBuilder};

// Include the Rust bindings generated by build.rs
#[allow(non_camel_case_types)]
#[allow(non_snake_case)]
#[allow(dead_code)]
mod lsm_enforcer {
    include!(concat!(env!("OUT_DIR"), "/lsm_enforcer.skel.rs"));
}

fn main() -> Result<()> {
    println!("🛡️ Starting Bouclier Bleu Core Engine...");

    // Build and open the BPF skeleton
    let skel_builder = lsm_enforcer::LsmEnforcerSkelBuilder::default();
    let open_skel = skel_builder.open()?;

    // Load the BPF program into the kernel
    let mut skel = open_skel.load()?;
    
    // Attach the LSM hook
    skel.attach()?;
    println!("· BPF LSM Hook attached successfully!");
    println!("· Run: # cat /sys/kernel/tracing/trace_pipe in another terminal to see alerts.");
    println!("Press Ctrl+C to exit.");

    // Keep the userland process alive so the BPF program stays attached
    loop {
        thread::sleep(Duration::from_secs(1));
    }
}
