// SPDX-License-Identifier: Apache-2.0
//
// Copyright 2026 The Bouclier Bleu Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use std::sync::atomic::{AtomicBool, Ordering};
use crate::SecurityModule;

/*
 * ExecBlock prevents the execution of binaries originating from world-writable 
 * directories (e.g., /tmp/, /dev/shm/). 
 * Threat Model:
 * Memory corruption exploits (buffer overflows) and web-shell stage droppers 
 * typically lack the privileges to write to secure paths like /usr/bin. They 
 * rely heavily on /tmp/ as a staging ground for secondary payloads. 
 * This module tracks alerts generated by the `exec_block.bpf.c` kernel hook.
 */
pub struct ExecBlock {
    // We use AtomicBool to ensure thread-safe lock-free toggling.
    // The BPF event router will read this concurrently while the CLI Control
    // Plane may attempt to write/toggle it.
    is_active: AtomicBool,
}

impl ExecBlock {
    pub fn new() -> Self {
        Self {
            // Modules fail-open to "active" to ensure protection on boot.
            is_active: AtomicBool::new(true),
        }
    }
    
    /*
     * Dynamically switches the operational state of the module.
     * Future Integration: When toggled, this method should also update an eBPF
     * shared Map (e.g., a `BPF_MAP_TYPE_ARRAY`) to notify the kernel-space
     * hook to stop enforcing the block, preventing unnecessary userland
     * context switches.
     */
    pub fn toggle(&mut self, state: bool) {
        self.is_active.store(state, Ordering::SeqCst);
        println!("Bouclier Bleu [Control]: ExecBlock active state -> {}", state);
    }
}

// Implement the default trait for clean instantiation
impl Default for ExecBlock {
    fn default() -> Self {
        Self::new()
    }
}

// Assuming you have a SecurityModule trait in modules/src/lib.rs
impl SecurityModule for ExecBlock {
    fn name(&self) -> &'static str {
        "Exec Block (/tmp, /dev/shm)"
    }

    fn status(&self) -> bool {
        // Ordering::Relaxed is sufficient for reading the state in the
        // hot-path to minimize CPU cache synchronization overhead.
        self.is_active.load(Ordering::Relaxed)
    }
    
    fn process_event(&self, _event_data: &[u8]) {
        if self.status() {
            /*
             * Architecture Note:
             * In the current PoC, the kernel hook returns -EPERM and logs via
             * bpf_printk.
             * Once the RingBuffer is implemented, this function will receive
             * a byte-slice of the `exec_alert` C-struct.
             * Example Workflow:
             * 1. Cast `_event_data` to `ExecAlertStruct`.
             * 2. Log the blocked filename to an enterprise SIEM.
             * 3. (Optional) Trigger `actions.rs` to forcefully kill the parent
             * PID that attempted to drop the payload.
             */
        }
    }
}
